### ISSUE TITLE
Illumina PF filtering not working 

### ISSUE THREAD

**Issue by mitros** [ExpressionAnalysis/ea-utils#45]
The only difference I see when I use the flag to remove CASAVA-filtered reads is in the log, reads with a Y in the filtered field remain in the output whether I use U or u

```
-U|u     Force disable/enable Illumina PF filtering (auto)
```

for instance, 
@HS2:86:D0D3KABXX:5:1104:19637:85303  2:Y:TTCTC
is in the output, even when using -u, or am I misunderstanding this option?

**Comment by ExpressionAnalysis** [comment]
Could you provide the command line that produced the error?  We cannot recreate the problem.
