### ISSUE TITLE
No output when running fastq-mcf

### ISSUE THREAD

**Issue by youngchan919** [ExpressionAnalysis/ea-utils#59]
Hello. An error arises when I was running fastq-mcf. Here is my command to run the program.

> ~/local/bin/fastq-mcf  /dev/null  ./test1.fastq.gz  -o ea1.fq -0 -R --qual-mean 20  -s 0 -l 33 -n

And the stdout is as follow:

> Command Line: /dev/null .../test1.fastq.gz -o ea1.fq -0 -R --qual-mean 20 -s 0 -l 33 -n
> Scale used: 0
> Phred: 33
> Threshold used: 1 out of 5
> No adapters found.

However, it confuses me that no file is generated. I am wondering if it is caused by wrong parameters or a bug. Thanks for your help.

**Comment by ExpressionAnalysis** [comment]
Hi!
The reason why you don't see output is because you are using the option -n which means don't clip

**Comment by youngchan919** [comment]
Thanks a lot!
